scss_files: 'src/**/*.scss'

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning



linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false

  BorderZero:
    enabled: false

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: false

  DeclarationOrder:
    enabled: false

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: false

  HexNotation:
    enabled: false

  HexValidation:
    enabled: false

  IdSelector:
    enabled: false

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: true
    character: space
    width: 4

  LeadingZero:
    enabled: false

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: false
    allow_leading_underscore: false
    convention: ^((\w+-{1,})*\w+|mdl-.+)$
    convention_explanation: 'Name should be written in lowercase with hyphens to separate words, with the exception of MDL classes.'

  NestingDepth:
    enabled: false

  PlaceholderInExtend:
    enabled: false

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertyCount:
    enabled: false

  PropertySortOrder:
    enabled: false
    #ignore_unspecified: false
    #min_properties: 2
    #separate_groups: true

  PropertySpelling:
    enabled: false

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'fr',                                    # Grid fractional lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%', 'cqmin']                                     # Other
    properties: {}

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  SelectorFormat:
    enabled: true
    convention: ^((\w+-{1,})*\w+|mdl-.+)$
    convention_explanation: 'Name should be written in lowercase with hyphens to separate words, with the exception of MDL classes.'

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: true
    style: at_least_one_space

  SpaceAfterComment:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: false

  SpaceAfterVariableColon:
    enabled: true
    style: one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: false

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: false

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers:
    excluded_identifiers:
      - user-select

  ZeroUnit:
    enabled: true
